apiVersion: v1
kind: Service
metadata:
  name: echo-exkube-svc
  namespace: exkube
spec:
  type: NodePort
  selector:
    app: echo-studentX
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31202
